---
#  - name: test stop qabbtqm servvef
#    service: 
#      name: rabbitmq-server
#      state: stopped
#
  - name: ensure python-software-properties is installed
    apt: 
        pkg: python-software-properties
        state: installed

  - name: add rabbitmq official apt repository
    apt_repository:
      repo: 'deb http://www.rabbitmq.com/debian/ testing main' 
      state: present

  - name: add trusted key
    apt_key: 
      url: https://www.rabbitmq.com/rabbitmq-release-signing-key.asc
      state: present

  - name: install package
    apt: 
      name: "{{ item }}" 
      update_cache: yes 
      state: installed
    with_items:
      - rabbitmq-server
    notify:
      - restart rabbitmq

  - name: enable rabbitmq plugins                                                                                                                ...
    rabbitmq_plugin: names=rabbitmq_management,rabbitmq_tracing,rabbitmq_mqtt state=enabled
    notify:
      - restart rabbitmq

  - name: add admin
    rabbitmq_user: user="admin" password="qwerty" tags=administrator, vhost=/ configure_priv=.* write_priv=.* read_priv=.* state=present

  - name: add client app
    rabbitmq_user: user="client_app" password="client_pass" vhost=/ configure_priv=.* write_priv=.* read_priv=.* state=present

...
