---
# minimal setup playbook so that Ansible can run

- hosts: VMs
  become: true
  gather_facts: False

  pre_tasks:

  - name: ensure minimal Python is installed
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal )

  tasks:

  - name: add some needed packages
    apt:
      name: "{{item}}"
      state: present

    with_items:

    - python-apt
    - python-pip
    - python-virtualenv
